### ISSUE TITLE
git version vs ms vscode marketplace version

### ISSUE THREAD

**Issue by bil74** [moosecasa/vscode-acutest-test-adapter#1]
Hi,
maybe it is not the proper place to bring this up, and most probably it is not your responsibility but i have found that the newest version in ms vscode extensions marketplace (which is used for download extensions from vscode itself) is not the really newest although it says it is v0.0.3.
I had problem using it and i figured out that it does not contain fix in commit named "**fixing windows users filesystem paths**" here.
I am not into js/ts so i did not install it from here (github), but only replaced uri.path to uri.fsPath in file C:\Users\xxx\\.vscode\extensions\moosecasa.vscode-acutest-test-adapter-0.0.3\out\Acutest.js and it worked.
(you can delete this as it is not an issue for this codebase, but i was unable to find a platform to post it, so i posted it here)
BR,
bil

**Comment by james2432** [comment]
I'll look into it, maybe I forgot to deploy it 🤔

**Comment by james2432** [comment]
Should be fixed now. I pushed a new version on both

**Comment by bil74** [comment]
Hi James, thank you for quick response!
I see the update (0.0.4), but still not working with the same error:
**Uncaught Errors (1)
ENOENT: no such file or directory, open '/c:/Users/xxx/vs_code_repo/cgyak/tests.c'**
(note the preceding '/' before c:)

I uninstalled previous versions and also deleted both extension directories under .vscode\extensions

**Comment by james2432** [comment]
Not sure why but it seems 
(vscode.workspace.workspaceFolders || [])[0].uri.fsPath;

Is returning a path starting with / i'll try to make a windows specific patch where it checks if it starts with / and removes it if needed. I compiled this exact code into the vsix

**Comment by bil74** [comment]
What i see is that in this file:
..\\.vscode\extensions\moosecasa.vscode-acutest-test-adapter-0.0.4\out\Acutest.js
there are two occurences of "uri.path". If i change both to "uri.fsPath", then all work.
This is with the newest extension (v0.0.4) downloaded directly from vscode.
So the problem i think is that uri.path is still there.
You can check it even on linux i think if you remove your extension and install the newest and you can check the content of the file i mentioned.

**Comment by james2432** [comment]
https://github.com/moosecasa/vscode-acutest-test-adapter/blob/master/src/Acutest.ts#L40
and
https://github.com/moosecasa/vscode-acutest-test-adapter/blob/master/src/Acutest.ts#L69

have been changed to fsPath, but it seems to now spitting out a / before the path now for some reason on windows

**Comment by bil74** [comment]
Well, i don't see the whole picture and how stuff goes from github to ms vscode extension repo.
It is good on github indeed, but if you download v0.0.4 from [ms repo](https://marketplace.visualstudio.com/items?itemName=Moosecasa.vscode-acutest-test-adapter) and change the extension to zip and unzip/browse the vsix inside, you can see that Acutest.js still contains uri.path.

**Comment by james2432** [comment]
Indeed for some reason the vsce is not compiling/bundling my code, I'll dig more into it

**Comment by james2432** [comment]
Figured out the issue, the 0.0.5 version should be working now

**Comment by bil74** [comment]
I can confirm it is working with version v0.0.6.
Thanks for you help James !

**Comment by james2432** [comment]
no problem!
